name: stacked_architecture
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  stacked: ^3.4.3
  stacked_services: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  mockito: ^5.4.4
  stacked_generator: ^1.6.1

flutter:
  uses-material-design: true

